"""
Writer Agent
------------
Generates structured output from research data.
Produces either a Short Summary or a Detailed Research Report.
"""

import time
from datetime import datetime


def writer_agent(research_data: dict, mode: str) -> dict:
    """
    Writer Agent: Formats research data into a polished report.

    Args:
        research_data: dict from searcher_agent
        mode: 'Short Summary' or 'Detailed Research Report'

    Returns:
        dict with formatted report sections
    """

    time.sleep(0.6)

    subject = research_data.get("subject", "Research Topic")
    title = research_data.get("title", f"Research on {subject}")
    timestamp = datetime.now().strftime("%B %d, %Y at %H:%M")

    sources = research_data.get("sources", [])

    # Build the appropriate report
    if mode == "Short Summary":
        report = _build_short_summary(
            title,
            research_data,
            timestamp
        )

    elif mode == "Detailed Research Report":
        report = _build_detailed_report(
            title,
            research_data,
            sources,
            timestamp
        )

    else:
        # Default to short summary for unknown modes
        report = _build_short_summary(
            title,
            research_data,
            timestamp
        )
        mode = "Short Summary"

    # Add common information
    report["sources"] = sources
    report["mode"] = mode
    report["title"] = title
    report["generated_at"] = timestamp
    report["status"] = "Report generated successfully"

    return report


def _build_short_summary(title, data, timestamp):
    """Build a concise summary report."""

    findings = data.get("key_findings", [])

    findings_text = "\n".join(
        f"• {finding}"
        for finding in findings[:3]
    )

    summary = f"""**{title}**
Generated: {timestamp}

**Executive Summary**
{data.get('abstract', '')}

**Top Findings**
{findings_text}

**Conclusion**
{data.get('conclusion', '')}
"""

    return {
        "executive_summary": data.get("abstract", ""),
        "key_findings": findings[:3],
        "conclusion": data.get("conclusion", ""),
        "full_text": summary,
        "word_count": len(summary.split()),
    }


def _build_detailed_report(title, data, sources, timestamp):
    """Build a comprehensive research report."""

    findings = data.get("key_findings", [])

    findings_text = "\n".join(
        f"{i + 1}. {finding}"
        for i, finding in enumerate(findings)
    )

    sources_text = "\n".join(
        f"[{i + 1}] "
        f"{source.get('title', 'Unknown title')} "
        f"({source.get('year', 'N/A')}) – "
        f"{source.get('venue', 'Unknown venue')} | "
        f"{source.get('url', 'No URL')}"
        for i, source in enumerate(sources)
    )

    full_text = f"""OPEN DEEP RESEARCH AGENT — RESEARCH REPORT
{'=' * 60}

Title  : {title}
Date   : {timestamp}
Mode   : Detailed Research Report

{'=' * 60}

1. INTRODUCTION
{data.get('abstract', '')}

2. METHODOLOGY
{data.get('methodology', '')}

3. RESEARCH FINDINGS
{findings_text}

4. ANALYSIS
{data.get('analysis', '')}

5. CONCLUSION
{data.get('conclusion', '')}

6. REFERENCES
{sources_text}

{'=' * 60}

Generated by Open Deep Research Agent | AI-Powered Research Automation System
"""

    return {
        "introduction": data.get("abstract", ""),
        "methodology": data.get("methodology", ""),
        "key_findings": findings,
        "analysis": data.get("analysis", ""),
        "conclusion": data.get("conclusion", ""),
        "references": sources,
        "full_text": full_text,
        "word_count": len(full_text.split()),
    }
